version: '3'
networks:
  spring-elk-net:
    external: true
services:
  elastic-search:
    image: elasticsearch:7.10.1
    container_name: cvl_elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - spring-elk-net
  kibana:
    image: kibana:7.10.1
    container_name: cvl_kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    networks:
      - spring-elk-net
  logstash-service:
    image: logstash:7.10.1
    container_name: 'logstash-service'
    restart: always
    ports:
      - 5000:5000
      - 5044:5044
      - 9600:9600
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elastic-search:9200
      - XPACK_MONITORING_ENABLED=true
    networks:
      - spring-elk-net
  micro1-sb-elk:
    image: cosdin/08-spring-elk:0.0.1-SNAPSHOT
    container_name: micro-sb-elk
    ports:
      - "8080:8080"
    restart: always
#    environment:
#      LOGSTASH_SERVICE_REMOTE_HOST: logstash-service
#      LOGSTASH_SERVICE_REMOTE_PORT: 5000
    networks:
      - spring-elk-net
